### ISSUE TITLE
♻️ Reconcilation Statuses

### ISSUE THREAD

**Issue by gluax** [monadicus/snarkops#141]
For the reconciliation process what we should instead do is:

- [x] agent reconcile RPC is short lived and returns an error, a requeue duration + status messages, or an OK
- [x] control plane has a global reconcile loop that walks a reconcile queue
- [x] env `prepare` (now `apply`) queues a reconcile for every agent

reasons:
- current reconcile logic dies if the rest request is closed 
- current reconcile logic depends on long lived RPC contexts
- current reconcile logic does not showing show clear status
- new reconcile can show where things fail
- new reconcile has better code smell (a Reconcile trait or something and more modular code)
- new reconcile concepts are more battle tested in devops land

**Comment by Meshiest** [comment]
completed in https://github.com/monadicus/snarkops/pull/315
