### ISSUE TITLE
✅ Scli Agent Apply Checkpoint

### ISSUE THREAD

**Issue by Slickbird** [monadicus/snarkops#181]
## ✅ Task

Commands to:
- reset the ledger
- apply a checkpoint

For an agent.

## Motivation

QOL for applying checkpoints manually.

## Details

Effects:
- `scli`
- `snops`

Cmds:
- `scli env agent foo reset-ledger`
- `scli env agent foo apply-checkpoint 1234`

Related to #182 and #183.

**Comment by Meshiest** [comment]
completed in https://github.com/monadicus/snarkops/pull/315
