### ISSUE TITLE
♻️ Prepare -> Apply

### ISSUE THREAD

**Issue by gluax** [monadicus/snarkops#192]
## ♻️ Refactor

We need to:
- rename `prepare` to `apply` in both cmds and endpoints.
- Then make a `prepare` that prepares all nodes in an offline state.

## Motivation

Separation of duties for clarity.

## Implementation

Effects:
- `snops`
- `scli`

**Comment by Meshiest** [comment]
completed in https://github.com/monadicus/snarkops/pull/315
