### ISSUE TITLE
✅ Read Bootstrap Peers

### ISSUE THREAD

**Issue by Slickbird** [monadicus/snarkops#197]
## ✅ Task

Reads bootstrap peers from a url/config file

## Motivation

To be able to easily configure peers for a node.

## Details

Also, add a config file to read peers from.
Add endpoint to re-read config file.

**Comment by Meshiest** [comment]
Requires forking snarkOS or compiling from a snarkOS fork...

**Comment by Meshiest** [comment]
would have been enabled by this PR https://github.com/AleoNet/snarkOS/pull/3397
