### ISSUE TITLE
✅ Split aot-runner to separate crate

### ISSUE THREAD

**Issue by Slickbird** [monadicus/snarkops#264]
## ✅ Task

Split aot-runner to its own crate.

## Motivation

Minimizing build times + separation of parts. A feature gate already separates runner, this just simplifies things.

## Implementation

Separate to it's own crate.
Will have to update Snops to handle both AOT and the Runner.

**Comment by gluax** [comment]
We are no longer splitting this:
- It didn't help with compile times
- It does make AOT smaller, but at the moment the big reason to do this was compile times.

This will also close #268 and #273.
